### ISSUE TITLE
APK not signed?

### ISSUE THREAD

**Issue by IzzySoft** [XilinJia/Life-Dots#4]
The APK on today's release (2.1.0) seems to be unsigned, can you please replace it with a signed one?

```
DOES NOT VERIFY
ERROR: Missing META-INF/MANIFEST.MF
2022-03-06 19:33:57,976 ERROR: 
repo/com.mdiqentw.lifedots_151.apk: 
2022-03-06 19:33:58,271 ERROR: Old APK signature failed to verify: repo/com.mdiqentw.lifedots_151.apk

no manifest.

jar is unsigned.
```

**Comment by XilinJia** [comment]
This is strange.  The release apk was installed on my phone without problem.  But when I verified it with keytool, I got report saying it's unsigned.

I just found a report saying AS Arctic Fox not building signed APK's with standard setting (though I am using Bumblebee): https://georgimirchev.com/2021/08/17/android-studio-arctic-fox-not-building-a-signed-apk/

I tried the solution by specifically adding the following into the signing config, then the apk is signed:
v1SigningEnabled true
v2SigningEnabled true

So the release apk is updated.

I also updated the setting in the build.gradle file, not sure if this will affect F-Droid builds.

**Comment by IzzySoft** [comment]
F-Droid's builds should not be affected at all (nit 100% sure, but we will see – F-Droid does its own signing). It was the updater in my repo which figured the problem – today the update succeeded, thanks to your replacing the APK (your app is [listed here](https://apt.izzysoft.de/fdroid/index/apk/com.mdiqentw.lifedots)). So thanks for your fast help – and as this issue is solved, I think we can close it.

PS: Once your app turns up at F-Droid, I'd usually remove it again from my repo. Should you for some reason prefer me to keep it, just let me know.
