### ISSUE TITLE
not installing

### ISSUE THREAD

**Issue by mrfricks** [XilinJia/Life-Dots#5]
hi it's not installing through fdroid or if I manually download the apk

**Comment by XilinJia** [comment]
Thank you for reporting the issue.  I reproduced the problem.  Sorry I didn't test directly installing the apk.  I just uploaded a new apk which works for me.  Please let me know if it also works for you.

The app is being launched on fdroid.  I am not sure if this build issue also occurs with them, but I will notify them.

**Comment by mrfricks** [comment]
hi @XilinJia ,  
the apk on github is now working.  👍
fdroid still not working for me but that maybe because of cached version.

thanks
